"""make sequence steps orderable

Revision ID: 5874ea3f51ab
Revises: e6d3fe40fbd3
Create Date: 2016-12-24 16:53:15.588801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5874ea3f51ab'
down_revision = 'e6d3fe40fbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_step', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sequence_step_order'), 'sequence_step', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_step_order'), table_name='sequence_step')
    op.drop_column('sequence_step', 'order')
    # ### end Alembic commands ###
