"""init migration

Revision ID: e6d3fe40fbd3
Revises: 
Create Date: 2016-12-24 11:06:57.934022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3fe40fbd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('temperature', sa.Float(precision=1), nullable=True),
    sa.Column('tolerance', sa.Float(precision=1), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('mixer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('sequence_step')
    # ### end Alembic commands ###
